default: &default
  encoding: utf8
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  template: template0
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>

development:
  <<: *default
  database: roga_challenge_development

test:
  <<: *default
  database: roga_challenge_test

production:
  <<: *default
  database: roga_challenge
